sudo: required
language: php
php:
- '7.0'
services:
- docker
before_install:
- chmod ugo+x ./build.sh
- docker-compose -f docker-compose.test.yml build --no-cache
- cp ./.env.test ./.env
- docker-compose -f docker-compose.test.yml run --rm workspace composer install
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif ["$TRAVIS_BRANCH"
  == "develop"]; then echo "stage"; else echo "dev-"$(git rev-parse --short HEAD);
  fi`
- "./build.sh $TAG"
env:
  global:
  - secure: LKSdLFiRF/lyjQcIv25rIUT/jVbcnYx6hlGGbwVwXrm1MJdw/FJfr1d79A2pnHD0GOrzK5I776CyIW+M5Oqw2X2uWpAq+TZ1r/vf1FHVSyi+xhpVSfvn57UGH1JDpXBJYPsHHL8KoHVzsm8pPmB0525atXUwaEoZ2z0bsXj/LGynNfIfBqsaaiaYmZT5jmsyLjydzk6for6lMqFeLH4AdG9eHjHUFP/kT6j/BiiapYADxh9PbacDSCbWH84RP5QjTPHKIzIdQjSyu35FA3v5zeY7SjF2FIRvEnVpXkW86rQC/fLot0hNqEw2DwZ0Tnhbtw469HcWRoF/iYBQKbXZmdoIL280i3mW8LCAjNL4RkdU7951xYrcVNP1Ufosir3MGp0tLtinCU+1M+tVLFuy0a/TNDamz5aqKfBdZUwSnEV+f2rCXw6sUQZNQo37BMbhsiwI45UE2D3bCk+poatVBRN04A16kQGuhWtAaGvMonHMzNm78zmIkHWf/hS0azUkxcshfIDg2rNbbnuZcCWVkBESfsPdZtjaTQeK/CqNElIhyLkwizFL/QJwyOVjFirbBGrAeLnYKfn8+riuVRp5hJbzrY9bgmUse6QgHrmS0iLHqrD2VkDsa2+zgLeJxwppFKl5SHcb1seUbfcifQYESrickcs5td5KSvJDjcsvhB4=
  - secure: nuWqhlvhHhy5cDxjhWPsj0eS2JlVhBGbpqv3bobI50QJrl9CXCbiKCpKovCS9Ak8I54xyokhkJjnf3930cdjzh58B/eQJ9dzkyyyApFvJYr4SKgGORsbrH3K1aQGeeLWrm5Jv87F80pHRNyLQc+txONdZhA+xbcx4jjzFH37t9zq/iu02lG1PuEPozlF2YULPVStE3mDNCPS4nPHZgQsSVZ+6KFvA+ZJ0U3tDrBXw03dbHTLGquZmX50WbznJLzftwFBqo087NdK43BmARGNQyc7fxOUp8gAgX0+bVqFY150eCFE3Fh9c1iFy7Ym6PmqbykiW7HDgtD/JDGi16mce4VrKJrhtGqYSAqk7cW9/n3aW0J2DNcR8DPQW3nJmVfTcFS+jfENsAp6/AyiljIhT/rzQxy22s+kjsh88bVImLVCvMrszwZwPmFHglTEN124W8BfECZeA6/EryhoxJPAbnEovUOAvzewjgZ3UqNk9vK+bhj34yXryuzU0jC0kOlNnyRKMvtzzULzigDMdiAkzc22rlAgqlCv4kg5NzWf0+OXE2JLlKfmeA84igtJWLz3MkQN7wEu3pdVw16Y5Q51NYnUa9MmWMGB7qUhzqPU590cdIxnhi/Y9TFmwMPZPqlBv1dENY9RRoho5HSbV5VEMov2944sufFZtaLegGPCYik=
notifications:
  slack:
    secure: i9vBnnAxS3i7Icee5PbCpfUeNnW5AdvxNprIygTcF8xtBQKafyF6AKFbQ58zGyoVm0EYez20f0uHBlmRaedgGt2Phwi+xA5WaRRi2X2bdbPIddFwy51TyWPZ4aUHh9ejqE0mq/5I/syc7tiVwMXyN7qQ+utgwZROxeCL9GR2Snhn5OiXgQoeC+5chy5M0pZU1VwwlDF+MxhG+2khSQ3nZhC6DbwPnEtvA4e4BAno6KgzLAwg7VHPs5+qH8iWfhdKm5gQb256goYO7CdHh2FqaAMvAy7bnvRpkzPkNOS4mSz2hZuFYavJku8APCqK7ljlUuzYgJ+SFElaNoX+zJUfWfBBuo6rboK+xtWe0J8AlvO1rIQ5oQo+6V0zw6x5fWOsRpqyOxgXdAZNgM3QXXogzAg0Le9HEuKtW3EG/XeN8IAD9iQWriZgmK+cjaqd0BYWfU362Z4KBTpn6qHVZp87TGR5S7YihMjebvk2UxBHc/hiT2KBS6LTHGe8i0iyHhAAgcMI7l7Taa6HQlK2u2YMpGetFPaedQ9LHZku2f9l93m+uALBXGKJkc064Lk2/KPZsq+nPoz3tYtHMKxS+6K1ZzqcuCgMBiUm3dOxN9xSruuliFj+kkrUjsvXuiguAjRUGLtST2PUWL61H2W5Fsy2Us71SHi9RzMnyOEj7s/iqyQ=
