sudo: required
language: php
php:
- '7.0'
services:
- docker
before_install:
- chmod ugo+x ./build.sh
- docker-compose -f docker-compose.test.yml build --no-cache
- cp ./.env.test ./.env
- docker-compose -f docker-compose.test.yml run --rm workspace composer install
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif ["$TRAVIS_BRANCH"
  == "develop"]; then echo "stage"; else echo "dev-"$(git rev-parse --short HEAD);
  fi`
- "./build.sh $TAG"
env:
  global:
  - secure: B2ZWp2W9SYAV0b6ud+D3Pws8p8e3LhGzv2d94226+I9VNyBRZOjnu/msNBTncgMuBc98GV7Rnk+BDBdhEAJch3+KF3yZeBDUEFouopmN7n7O0ECu21zkjM4BKsH86PU139xsynMjCf/idekAO3bAEqFV4i+Sodd+50r8k9zvvxQbMVCT+APiJRjChj2t4NX1Vk2A+TrKdVH0G6cRvnrqNVJiOrEG2ox1+Q7puuCzjxKwjl8TPwq9V86pCIFZNJlxUbdCziemdu0gavcd+gnGAA73u2sfPq16JH8A/EiOCussDcbEmsLF+txNTt0whHPEJWpqquRrOp947XkTrB9RWuTE9JpNbr5ctRHZ+LYdZd9mxOBKx48BQCiV5VCfPLAySOuZzxmke7tgujT9ZFECb6TwbPVX++rpIoXAiVPX/FvI5GhL5r7FRLRivnO7A0nRT4tRx+fldMUJqajzRnMUvIzL7qqbanj1o4VCaPOyx4yk1mVhxTnwcNSV7yfuJ27feEv8TYeGw/vxviAM8Hhv4u64d0sjaqC57uNujucxEGxHsZJwBJ8YFQDBY0N3+fLVfbwhNiid2Z8LwnnYIRl7J+3hRKCJjNVf9V70XAFCEjR3I2yZ2ciuoqL48AEVF2PC86450mNnZTlbSvqFZ9jDakDricqTbGTbZkPZ+EYQ71o=
  - secure: euGfjubDaOFRQLIfF8PTDPaWhELXt4KDgc6Lvm5kx9vxLm+K06OUsbrkFtdYJWMzKodbsO4ga2MMh8ql6qhenWg/q3hxPGjCki0gHVsiZFSBQhMOOu8/Y5Hn76fJekNYzoPew9ZnEjTovH+ZRRqNxFSF+lFhScXhMp014g1WO7e3CAC6KY3dCMrlHcm008YnrETi054GJ1oLHOg+s9DUeRKzp9HFz/lLdY1FFUiSPQ774OnyHn6tBe5AVfNbJYNGCTEVAnBr/9liaZr3SYqfhM+4sijQ0Dx3s8Fh6E4gukDQLTfQrv19p96iMNLW3RENIKs3u2mMEU86E5N0E3Qk33lk+WWgQP5+AuVPMeCd/geGv3Sp5IXBVPLJDYKx1hzAEdR+5fhBl2U2vdL6xUNQMrghP9wLJ8eLe0Hh0Cx7IX/x/UFK3rri3jlvPZ9byk/EdvrUDXhM0JKIIxl3TVE9Nn9JjcvrLdNO8MGIThKLX2hxV2us3+WQE1LZoEjDZPTfIbwc/0xNVk5msGbuEPdzTgwr/RQlqkPCVC05riAViJwDT4RKWMtcQXmhCp921RQL5VLDgZx/VmNGicKcqhoBphbOiPidmQCF+6G/ei0rHQomGQZLNnDpr0/ey189U+abjv1SMEikgi0xorAmu+c8ylvTMmNQyGZbnkkm//m7cO4=
notifications:
  slack:
    secure: i9vBnnAxS3i7Icee5PbCpfUeNnW5AdvxNprIygTcF8xtBQKafyF6AKFbQ58zGyoVm0EYez20f0uHBlmRaedgGt2Phwi+xA5WaRRi2X2bdbPIddFwy51TyWPZ4aUHh9ejqE0mq/5I/syc7tiVwMXyN7qQ+utgwZROxeCL9GR2Snhn5OiXgQoeC+5chy5M0pZU1VwwlDF+MxhG+2khSQ3nZhC6DbwPnEtvA4e4BAno6KgzLAwg7VHPs5+qH8iWfhdKm5gQb256goYO7CdHh2FqaAMvAy7bnvRpkzPkNOS4mSz2hZuFYavJku8APCqK7ljlUuzYgJ+SFElaNoX+zJUfWfBBuo6rboK+xtWe0J8AlvO1rIQ5oQo+6V0zw6x5fWOsRpqyOxgXdAZNgM3QXXogzAg0Le9HEuKtW3EG/XeN8IAD9iQWriZgmK+cjaqd0BYWfU362Z4KBTpn6qHVZp87TGR5S7YihMjebvk2UxBHc/hiT2KBS6LTHGe8i0iyHhAAgcMI7l7Taa6HQlK2u2YMpGetFPaedQ9LHZku2f9l93m+uALBXGKJkc064Lk2/KPZsq+nPoz3tYtHMKxS+6K1ZzqcuCgMBiUm3dOxN9xSruuliFj+kkrUjsvXuiguAjRUGLtST2PUWL61H2W5Fsy2Us71SHi9RzMnyOEj7s/iqyQ=
