sudo: required
language: php
php:
- '7.0'
services:
- docker
before_install:
- chmod ugo+x ./build.sh
- docker-compose -f docker-compose.test.yml build --no-cache
- cp ./.env.test ./.env
- docker-compose -f docker-compose.test.yml run --rm workspace composer install
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif ["$TRAVIS_BRANCH"
  == "develop"]; then echo "stage"; else echo "dev-"$(git rev-parse --short HEAD);
  fi`
- "./build.sh $TAG"
env:
  global:
  - secure: KPOdtfQB2kx549U3NTX3eJHC+ENwF1QjA+QkAPpkqQGKV/AiCaEFjl+Tzafiw1PuSnKnD6zDQr44Me+o6iHoT39pwbfxnCCUD3qRh72jVQYXeqTpdE453T0sJPCSxTSEhdlnXOgCxISWKjLCOIO5JjUgfiu6RbU91sW4+d7gabAsKnSWOco3kbQQIZRkmgXJWcYcx7b7raEgp5Eaa1jjLimc2s36PrV7M3vdM5gcdJPSYy+0x5reDWKUEpdFs3xWq6bKYWFrt+sGrQZKUgoUqbelIkpAdjeowxQeMq0cMXk5KHf3RJ88G1njmTzwF2kYuWiGuqyEgURtLzGKH+WtIUQOIN31f7dyUdYixjpFNk+Um6OT6F778p9Qwz7n893B01cCz+T9M31RQWddPKegZVomuxiJxILoTyd8Sr2aABc7GTYMng7jj9x+2g8CQxDtDEI2oTUtRm2d3KzU0T6dY3fhyrP/yzqD8A68yOASm9O8k5txISDB4QoUvcTC/xgX3ZJbpcXWIfNxWjoSXBY84F1TXQoyfdAlscdDn50ZpTyRniykjcrnsT+1MJ0esVyj2GXJbcqg7z61gT3L3od7UrpASWa193v+pUEdxteDLvcyTHnsFwQKYKFrhr6y8918hPB/X6y8qiNT3wxZmAdbHZZc62SlpxIicxUd432ksAQ=
  - secure: eBlZJbf65u9Wl+OKHy+fekHxo6tM+fAooOKeVPy0OK8qBx8MevddNOYyBTb8NdntCT1algy3GDJ7qQQxYGY868QCPxt3pQg09BmVmFj8YbNYO06Xa5qz+orH4NqD6ZRwLV7yXyHSQC5zG2m0rdbCMnP6hP5j4U+5Hi+sfgwJSHgsGlZYQwStL34ID89AYjWhdB0jv8krsORSNst6pIkLmdoPqNj5GHiIc8m/NBEKMKgcH14s4C6OAb2x81rkdDpAvZvfpmmOIpqSWKpA3cqqpD+6MjABSnq/fzrHWK8TyXOYtiQIUeI0Bn1AdtN4OBCuoaY9bGxTdjevE+9jjjhYxe6JuGhm0AR685rKzOoUhCiIqrX8gNjAe72AYX7kQV9ogDGY/QTTOyA/PC1hMp9SaSzJj/P0HgFsPKRvoXvvjafD2yh9QgX9akqKqqIhlEEPclyPS+KAdBnTTBc5S1mLuiNbo3jsUWn+vah/jPRUX3YOpElVSprN810ayAlNr1db6EUf5YQak0yqtFgeR05PW+qHDigDDb+97Tqg9GRmC7FL3bL3wUP/Assq3USBGRdnB37oKjhml+VtVliL5xUo7+N1MlX3/YN7PkQl91SJjQpd6fdniXdQ8FKJgtuqZ4YfYG62KSUT7vYQNMF+a509h47B/P7S8H0i1nXBXvfe4cE=
notifications:
  slack:
    secure: i9vBnnAxS3i7Icee5PbCpfUeNnW5AdvxNprIygTcF8xtBQKafyF6AKFbQ58zGyoVm0EYez20f0uHBlmRaedgGt2Phwi+xA5WaRRi2X2bdbPIddFwy51TyWPZ4aUHh9ejqE0mq/5I/syc7tiVwMXyN7qQ+utgwZROxeCL9GR2Snhn5OiXgQoeC+5chy5M0pZU1VwwlDF+MxhG+2khSQ3nZhC6DbwPnEtvA4e4BAno6KgzLAwg7VHPs5+qH8iWfhdKm5gQb256goYO7CdHh2FqaAMvAy7bnvRpkzPkNOS4mSz2hZuFYavJku8APCqK7ljlUuzYgJ+SFElaNoX+zJUfWfBBuo6rboK+xtWe0J8AlvO1rIQ5oQo+6V0zw6x5fWOsRpqyOxgXdAZNgM3QXXogzAg0Le9HEuKtW3EG/XeN8IAD9iQWriZgmK+cjaqd0BYWfU362Z4KBTpn6qHVZp87TGR5S7YihMjebvk2UxBHc/hiT2KBS6LTHGe8i0iyHhAAgcMI7l7Taa6HQlK2u2YMpGetFPaedQ9LHZku2f9l93m+uALBXGKJkc064Lk2/KPZsq+nPoz3tYtHMKxS+6K1ZzqcuCgMBiUm3dOxN9xSruuliFj+kkrUjsvXuiguAjRUGLtST2PUWL61H2W5Fsy2Us71SHi9RzMnyOEj7s/iqyQ=
