version: '2'
services:

  workspace:
    build:
      context: ./
      args:
        - TZ=UTC
        - INSTALL_XDEBUG=true
      dockerfile: workspace.docker
    tty: true
    links:
      - mongo
      - auth
      - redis
    volumes_from:
      - src
    ports:
      - 8000:8000
    environment:
      - PHP_IDE_CONFIG="serverName=companies"
    networks:
      default:
        ipv4_address: 10.10.0.4

  auth:
      image: registry.jincor.com/backend/auth:latest
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        THROTTLER_WHITE_LIST: 127.0.0.1,10.10.0.2,10.10.0.3,10.10.0.4
        TENANT_WHITE_LIST: 127.0.0.1,10.10.0.2,10.10.0.3,10.10.0.4
        FORCE_HTTPS: disabled
        JWT_KEY: "7z3B4gLdSx#fTlAmNnfrYC-;Gp#7fXfOk@cehjUHTWhDjSdcp1"
      volumes:
        - /usr/src/app
      links:
        - redis
      networks:
        default:
          ipv4_address: 10.10.0.5

  redis:
      image: registry.jincor.com/backend/redis:latest
      volumes:
            - ./storage/redis:/data
      networks:
        default:
          ipv4_address: 10.10.0.7

  mongo:
      image: registry.jincor.com/backend/mongodb:latest
      volumes:
            - ./storage/mongodb:/data/db
      networks:
        default:
          ipv4_address: 10.10.0.2
      ports:
        - 27017:27017
        - 28017:28017

  src:
    image: tianon/true
    volumes:
      - ./:/var/www/jincor_admin
    networks:
      default:
        ipv4_address: 10.10.0.3

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1