version: '2'
services:

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
      - ./storage/mongodb:/data/db

  workspace:
    build:
      context: ./
      dockerfile: workspace.test
    tty: true
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./:/var/www/jincor_admin
